apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: markdown-ingress 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.markdown.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: markdown-service
            port:
              number: {{ .Values.markdown.port }} 