
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: markdown-editor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ariefshaik7/nextjs-k8s.git'
    path: 'helm/markdown-chart'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: markdown
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 